// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtKiS7NYzXguZc0RqrtiuhLhQzoMyd4v8',
    appId: '1:988321571107:web:0a21296ebc191b52196c96',
    messagingSenderId: '988321571107',
    projectId: 'vitaring-49c16',
    authDomain: 'vitaring-49c16.firebaseapp.com',
    storageBucket: 'vitaring-49c16.firebasestorage.app',
    measurementId: 'G-PGLKKPBBM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAzwgcQaFoScJtQDxBVCRMRqsQQp_sHP4',
    appId: '1:988321571107:android:27c51cd8377618b4196c96',
    messagingSenderId: '988321571107',
    projectId: 'vitaring-49c16',
    storageBucket: 'vitaring-49c16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgOVIEGcbBE7PndpPjZcVmLDKofJafxss',
    appId: '1:988321571107:ios:7a9e8f43718c3313196c96',
    messagingSenderId: '988321571107',
    projectId: 'vitaring-49c16',
    storageBucket: 'vitaring-49c16.firebasestorage.app',
    iosBundleId: 'com.example.adminVitaring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgOVIEGcbBE7PndpPjZcVmLDKofJafxss',
    appId: '1:988321571107:ios:7a9e8f43718c3313196c96',
    messagingSenderId: '988321571107',
    projectId: 'vitaring-49c16',
    storageBucket: 'vitaring-49c16.firebasestorage.app',
    iosBundleId: 'com.example.adminVitaring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtKiS7NYzXguZc0RqrtiuhLhQzoMyd4v8',
    appId: '1:988321571107:web:623667df956424ab196c96',
    messagingSenderId: '988321571107',
    projectId: 'vitaring-49c16',
    authDomain: 'vitaring-49c16.firebaseapp.com',
    storageBucket: 'vitaring-49c16.firebasestorage.app',
    measurementId: 'G-GF5HJ6S0S7',
  );

}